stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - vendor
    - bin

build:
  stage: build
  script:
    - composer update

test:
  stage: test
  script:
    - phpcs --colors --standard=PSR1,PSR2 --encoding=utf-8 --tab-width=4 ./src
    - phpcs --colors --standard=PSR1,PSR2 --encoding=utf-8 --tab-width=4 ./tests
    - phpunit
